services: docker
language: node_js
git:
  depth: 1
  quiet: true

before_script:
    - curl -O https://raw.githubusercontent.com/cyber-dojo/cyber-dojo/master/shared/push_and_trigger.sh
    - chmod +x push_and_trigger.sh

script:
    - ./pipe_build_up_test.sh \
        && ./push_and_trigger.sh cyber-dojo/web
